const MIN_AMOUNT_TEAMS = 2;
const MAX_AMOUNT_TEAMS = 256;
const MIN_AMOUNT_PLAYERS = 1;
const MAX_AMOUNT_PLAYERS = 128;

export default {
	MIN_AMOUNT_TEAMS: MIN_AMOUNT_TEAMS,
	MAX_AMOUNT_TEAMS: MAX_AMOUNT_TEAMS,
	MIN_AMOUNT_PLAYERS: MIN_AMOUNT_PLAYERS,
	MAX_AMOUNT_PLAYERS: MAX_AMOUNT_PLAYERS
};
